-- Generated by packages/ui/tools/make-template.mjs - run it in Aseprite (File > Scripts) to add the template's slices.
-- Each slice is one frame of the game's UI atlas, named as the skin names it; a slice with a nine-patch centre is a frame that stretches (its centre is the part that grows).
local TEMPLATE = "C:/Documents/projects/vc_projects/logic-incubator/packages/ui/art/ui-template.png"
local TARGET = "C:/Documents/projects/vc_projects/logic-incubator/packages/ui/art/ui.aseprite"
local WIDTH, HEIGHT = 512, 520
-- name, x, y, width, height, centre x, y, width, height (or nil), then the slice's display colour
local SLICES = {
  { "btn_confirm_normal", 8, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_confirm_hover", 32, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_confirm_pressed", 56, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_confirm_disabled", 80, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_danger_normal", 104, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_danger_hover", 128, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_danger_pressed", 152, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_danger_disabled", 176, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_icon_normal", 200, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_icon_hover", 224, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_icon_pressed", 248, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_icon_disabled", 272, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_primary_normal", 296, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_primary_hover", 320, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_primary_pressed", 344, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_primary_disabled", 368, 24, 14, 14, 6, 6, 2, 2, 106, 96, 196 },
  { "btn_secondary_normal", 392, 24, 14, 12, 6, 5, 2, 2, 106, 96, 196 },
  { "btn_secondary_hover", 416, 24, 14, 12, 6, 5, 2, 2, 106, 96, 196 },
  { "btn_secondary_pressed", 440, 24, 14, 12, 6, 5, 2, 2, 106, 96, 196 },
  { "btn_secondary_disabled", 464, 24, 14, 12, 6, 5, 2, 2, 106, 96, 196 },
  { "btn_small_normal", 488, 24, 12, 12, 5, 5, 2, 2, 106, 96, 196 },
  { "btn_small_hover", 8, 48, 12, 12, 5, 5, 2, 2, 106, 96, 196 },
  { "btn_small_pressed", 32, 48, 12, 12, 5, 5, 2, 2, 106, 96, 196 },
  { "btn_small_disabled", 56, 48, 12, 12, 5, 5, 2, 2, 106, 96, 196 },
  { "dialogue", 8, 96, 18, 18, 8, 8, 2, 2, 96, 160, 196 },
  { "dialogue_arrow", 40, 96, 10, 7, nil, nil, nil, nil, 96, 160, 196 },
  { "panel_plain", 64, 96, 18, 18, 8, 8, 2, 2, 96, 160, 196 },
  { "portrait_frame", 96, 96, 10, 10, 4, 4, 2, 2, 96, 160, 196 },
  { "toast_bad", 120, 96, 18, 18, 8, 8, 2, 2, 96, 160, 196 },
  { "toast_good", 152, 96, 18, 18, 8, 8, 2, 2, 96, 160, 196 },
  { "tooltip", 184, 96, 18, 18, 8, 8, 2, 2, 96, 160, 196 },
  { "tooltip_tail_down", 216, 96, 11, 6, nil, nil, nil, nil, 96, 160, 196 },
  { "tooltip_tail_up", 240, 96, 11, 6, nil, nil, nil, nil, 96, 160, 196 },
  { "window_title", 264, 96, 14, 14, 6, 6, 2, 2, 96, 160, 196 },
  { "border_chain_cap_l", 8, 152, 12, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_chain_cap_r", 32, 152, 12, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_chain_centre", 56, 152, 18, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_chain_mid", 88, 152, 8, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_cap_l", 104, 152, 8, 13, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_cap_r", 120, 152, 8, 13, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_centre", 136, 152, 26, 13, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_mid", 176, 152, 1, 13, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_cap_l", 192, 152, 6, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_cap_r", 208, 152, 6, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_centre", 224, 152, 27, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_mid", 264, 152, 15, 15, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_cap_l", 288, 152, 6, 8, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_cap_r", 304, 152, 6, 8, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_centre", 320, 152, 9, 8, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_mid", 344, 152, 1, 8, nil, nil, nil, nil, 160, 106, 196 },
  { "bar_fill_amber", 8, 200, 2, 7, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_fill_blue", 24, 200, 2, 7, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_fill_green", 40, 200, 2, 7, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_fill_red", 56, 200, 2, 7, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_track", 72, 200, 8, 8, 3, 3, 2, 2, 196, 96, 96 },
  { "checkbox_off", 8, 240, 14, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_on", 32, 240, 14, 14, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_off_hover", 56, 240, 14, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_off_disabled", 80, 240, 14, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_on_hover", 104, 240, 14, 14, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_on_disabled", 128, 240, 15, 13, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_off", 152, 240, 12, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_on", 176, 240, 12, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_off_hover", 200, 240, 12, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_off_disabled", 224, 240, 12, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_on_hover", 248, 240, 12, 15, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_on_disabled", 272, 240, 12, 12, nil, nil, nil, nil, 96, 196, 128 },
  { "scroll_thumb_normal", 8, 288, 12, 12, 5, 5, 2, 2, 196, 176, 96 },
  { "scroll_thumb_hover", 32, 288, 12, 12, 5, 5, 2, 2, 196, 176, 96 },
  { "scroll_thumb_pressed", 56, 288, 12, 12, 5, 5, 2, 2, 196, 176, 96 },
  { "scroll_thumb_disabled", 80, 288, 12, 12, 5, 5, 2, 2, 196, 176, 96 },
  { "scroll_track", 104, 288, 8, 8, 3, 3, 2, 2, 196, 176, 96 },
  { "slider_thumb_normal", 120, 288, 12, 16, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_thumb_hover", 144, 288, 12, 16, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_thumb_pressed", 168, 288, 12, 16, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_thumb_disabled", 192, 288, 12, 16, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_track", 216, 288, 8, 8, 3, 3, 2, 2, 196, 176, 96 },
  { "tab_inactive", 8, 336, 12, 12, 5, 5, 2, 2, 96, 196, 196 },
  { "tab_active", 32, 336, 14, 14, 6, 6, 2, 2, 96, 196, 196 },
  { "tab_hover", 56, 336, 12, 12, 5, 5, 2, 2, 96, 196, 196 },
  { "tab_disabled", 80, 336, 12, 12, 5, 5, 2, 2, 96, 196, 196 },
  { "field_normal", 8, 384, 14, 14, 6, 6, 2, 2, 196, 128, 96 },
  { "field_focused", 32, 384, 14, 14, 6, 6, 2, 2, 196, 128, 96 },
  { "field_disabled", 56, 384, 14, 14, 6, 6, 2, 2, 196, 128, 96 },
  { "slot_empty", 8, 432, 10, 10, 4, 4, 2, 2, 128, 196, 96 },
  { "slot_hover", 32, 432, 10, 10, 4, 4, 2, 2, 128, 196, 96 },
  { "slot_selected", 56, 432, 10, 10, 4, 4, 2, 2, 128, 196, 96 },
  { "slot_disabled", 80, 432, 10, 10, 4, 4, 2, 2, 128, 196, 96 },
  { "icon_arrow_down", 8, 480, 16, 17, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_arrow_left", 32, 480, 17, 16, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_arrow_right", 64, 480, 17, 16, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_arrow_up", 96, 480, 16, 17, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_close", 120, 480, 14, 16, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_gear", 144, 480, 17, 15, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_heart_empty", 176, 480, 13, 13, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_heart_full", 200, 480, 13, 12, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_heart_half", 224, 480, 13, 13, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_music", 248, 480, 14, 16, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_orb_empty", 272, 480, 14, 12, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_orb_full", 296, 480, 12, 12, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_pause", 320, 480, 14, 14, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_speaker", 344, 480, 16, 16, nil, nil, nil, nil, 196, 96, 176 },
}

local sprite = app.activeSprite
if sprite == nil or sprite.width ~= WIDTH or sprite.height ~= HEIGHT then
  sprite = Sprite{ fromFile = TEMPLATE, oneFrame = true }
end
if #sprite.slices > 0 then
  app.alert("This sprite already has slices, so nothing was added. Open ui-template.png afresh to start over.")
  return
end

app.transaction(function()
  for _, s in ipairs(SLICES) do
    local slice = sprite:newSlice(Rectangle(s[2], s[3], s[4], s[5]))
    slice.name = s[1]
    if s[6] ~= nil then
      slice.center = Rectangle(s[6], s[7], s[8], s[9])
    end
    slice.color = Color{ r = s[10], g = s[11], b = s[12], a = 255 }
  end
end)

local saved = ""
if app.fs.isFile(TARGET) then
  saved = "\n" .. TARGET .. " already exists, so the sprite was not saved over it (File > Save As to keep this one)."
else
  sprite:saveAs(TARGET)
  saved = "\nSaved as " .. TARGET
end
app.alert("Added " .. #SLICES .. " slices." .. saved)
