-- Generated by packages/ui/tools/make-template.mjs - run it in Aseprite (File > Scripts) to add the template's slices.
-- Each slice is one frame of the game's UI atlas, named as the skin names it; a slice with a nine-patch centre is a frame that stretches (its centre is the part that grows).
local TEMPLATE = "C:/Documents/projects/vc_projects/logic-incubator/packages/ui/art/ui-template.png"
local TARGET = "C:/Documents/projects/vc_projects/logic-incubator/packages/ui/art/ui.aseprite"
local WIDTH, HEIGHT = 768, 1616
-- name, x, y, width, height, centre x, y, width, height (or nil), then the slice's display colour
local SLICES = {
  { "btn_confirm_normal", 8, 24, 167, 52, 12, 12, 143, 28, 106, 96, 196 },
  { "btn_confirm_hover", 184, 24, 167, 52, 12, 12, 143, 28, 106, 96, 196 },
  { "btn_confirm_pressed", 360, 24, 167, 52, 12, 12, 143, 28, 106, 96, 196 },
  { "btn_confirm_disabled", 536, 24, 167, 52, 12, 12, 143, 28, 106, 96, 196 },
  { "btn_danger_normal", 8, 88, 186, 52, 12, 12, 162, 28, 106, 96, 196 },
  { "btn_danger_hover", 208, 88, 186, 52, 12, 12, 162, 28, 106, 96, 196 },
  { "btn_danger_pressed", 408, 88, 186, 52, 12, 12, 162, 28, 106, 96, 196 },
  { "btn_danger_disabled", 8, 152, 186, 52, 12, 12, 162, 28, 106, 96, 196 },
  { "btn_icon_normal", 208, 152, 46, 49, 12, 12, 22, 25, 106, 96, 196 },
  { "btn_icon_hover", 264, 152, 46, 49, 12, 12, 22, 25, 106, 96, 196 },
  { "btn_icon_pressed", 320, 152, 46, 49, 12, 12, 22, 25, 106, 96, 196 },
  { "btn_icon_disabled", 376, 152, 46, 49, 12, 12, 22, 25, 106, 96, 196 },
  { "btn_primary_normal", 432, 152, 186, 52, 12, 12, 162, 28, 106, 96, 196 },
  { "btn_primary_hover", 8, 216, 167, 52, 12, 12, 143, 28, 106, 96, 196 },
  { "btn_primary_pressed", 184, 216, 186, 48, 12, 12, 162, 24, 106, 96, 196 },
  { "btn_primary_disabled", 384, 216, 161, 47, 12, 12, 137, 23, 106, 96, 196 },
  { "btn_secondary_normal", 8, 280, 206, 42, 12, 10, 182, 22, 106, 96, 196 },
  { "btn_secondary_hover", 224, 280, 206, 42, 12, 10, 182, 22, 106, 96, 196 },
  { "btn_secondary_pressed", 440, 280, 206, 42, 12, 10, 182, 22, 106, 96, 196 },
  { "btn_secondary_disabled", 8, 336, 206, 42, 12, 10, 182, 22, 106, 96, 196 },
  { "btn_small_normal", 224, 336, 138, 37, 10, 10, 118, 17, 106, 96, 196 },
  { "btn_small_hover", 376, 336, 138, 37, 10, 10, 118, 17, 106, 96, 196 },
  { "btn_small_pressed", 528, 336, 138, 37, 10, 10, 118, 17, 106, 96, 196 },
  { "btn_small_disabled", 8, 392, 138, 37, 10, 10, 118, 17, 106, 96, 196 },
  { "dialogue", 8, 464, 285, 135, 16, 16, 253, 103, 96, 160, 196 },
  { "dialogue_arrow", 304, 464, 19, 15, nil, nil, nil, nil, 96, 160, 196 },
  { "panel_plain", 336, 464, 277, 182, 16, 16, 245, 150, 96, 160, 196 },
  { "portrait_frame", 624, 464, 54, 52, 8, 8, 38, 36, 96, 160, 196 },
  { "toast_bad", 8, 656, 248, 67, 16, 16, 216, 35, 96, 160, 196 },
  { "toast_good", 264, 656, 248, 62, 16, 16, 216, 30, 96, 160, 196 },
  { "tooltip", 520, 656, 212, 106, 16, 16, 180, 74, 96, 160, 196 },
  { "tooltip_tail_down", 8, 776, 23, 12, nil, nil, nil, nil, 96, 160, 196 },
  { "tooltip_tail_up", 40, 776, 23, 12, nil, nil, nil, nil, 96, 160, 196 },
  { "window_title", 72, 776, 190, 37, 12, 12, 166, 13, 96, 160, 196 },
  { "border_chain_cap_l", 8, 848, 24, 30, nil, nil, nil, nil, 160, 106, 196 },
  { "border_chain_cap_r", 40, 848, 24, 30, nil, nil, nil, nil, 160, 106, 196 },
  { "border_chain_centre", 72, 848, 36, 30, nil, nil, nil, nil, 160, 106, 196 },
  { "border_chain_mid", 120, 848, 15, 30, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_cap_l", 144, 848, 16, 26, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_cap_r", 168, 848, 16, 26, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_centre", 192, 848, 52, 26, nil, nil, nil, nil, 160, 106, 196 },
  { "border_dotted_mid", 256, 848, 1, 26, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_cap_l", 272, 848, 12, 29, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_cap_r", 296, 848, 12, 29, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_centre", 320, 848, 54, 29, nil, nil, nil, nil, 160, 106, 196 },
  { "border_double_mid", 384, 848, 1, 29, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_cap_l", 400, 848, 12, 17, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_cap_r", 424, 848, 12, 17, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_centre", 448, 848, 18, 17, nil, nil, nil, nil, 160, 106, 196 },
  { "border_thin_mid", 480, 848, 1, 17, nil, nil, nil, nil, 160, 106, 196 },
  { "bar_fill_amber", 8, 912, 4, 14, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_fill_blue", 24, 912, 4, 14, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_fill_green", 40, 912, 4, 14, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_fill_red", 56, 912, 4, 14, nil, nil, nil, nil, 196, 96, 96 },
  { "bar_track", 72, 912, 170, 22, 6, 6, 158, 10, 196, 96, 96 },
  { "checkbox_off", 8, 968, 28, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_on", 48, 968, 28, 28, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_off_hover", 88, 968, 28, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_off_disabled", 128, 968, 28, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_on_hover", 168, 968, 28, 28, nil, nil, nil, nil, 96, 196, 128 },
  { "checkbox_on_disabled", 208, 968, 30, 26, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_off", 248, 968, 25, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_on", 288, 968, 24, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_off_hover", 320, 968, 25, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_off_disabled", 360, 968, 25, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_on_hover", 400, 968, 24, 29, nil, nil, nil, nil, 96, 196, 128 },
  { "radio_on_disabled", 432, 968, 24, 25, nil, nil, nil, nil, 96, 196, 128 },
  { "scroll_thumb_normal", 8, 1032, 138, 37, 10, 10, 118, 17, 196, 176, 96 },
  { "scroll_thumb_hover", 160, 1032, 138, 37, 10, 10, 118, 17, 196, 176, 96 },
  { "scroll_thumb_pressed", 312, 1032, 138, 37, 10, 10, 118, 17, 196, 176, 96 },
  { "scroll_thumb_disabled", 464, 1032, 138, 37, 10, 10, 118, 17, 196, 176, 96 },
  { "scroll_track", 616, 1032, 22, 170, 6, 6, 10, 158, 196, 176, 96 },
  { "slider_thumb_normal", 648, 1032, 24, 32, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_thumb_hover", 680, 1032, 24, 32, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_thumb_pressed", 712, 1032, 24, 32, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_thumb_disabled", 8, 1216, 24, 32, nil, nil, nil, nil, 196, 176, 96 },
  { "slider_track", 40, 1216, 170, 22, 6, 6, 158, 10, 196, 176, 96 },
  { "tab_inactive", 8, 1280, 62, 36, 10, 10, 42, 16, 96, 196, 196 },
  { "tab_active", 80, 1280, 107, 38, 12, 12, 83, 14, 96, 196, 196 },
  { "tab_hover", 200, 1280, 62, 36, 10, 10, 42, 16, 96, 196, 196 },
  { "tab_disabled", 272, 1280, 62, 36, 10, 10, 42, 16, 96, 196, 196 },
  { "field_normal", 8, 1352, 350, 34, 12, 12, 326, 10, 196, 128, 96 },
  { "field_focused", 368, 1352, 350, 34, 12, 12, 326, 10, 196, 128, 96 },
  { "field_disabled", 8, 1400, 350, 34, 12, 12, 326, 10, 196, 128, 96 },
  { "slot_empty", 8, 1472, 54, 52, 8, 8, 38, 36, 128, 196, 96 },
  { "slot_hover", 72, 1472, 54, 52, 8, 8, 38, 36, 128, 196, 96 },
  { "slot_selected", 136, 1472, 54, 52, 8, 8, 38, 36, 128, 196, 96 },
  { "slot_disabled", 200, 1472, 54, 52, 8, 8, 38, 36, 128, 196, 96 },
  { "icon_arrow_down", 8, 1560, 32, 34, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_arrow_left", 48, 1560, 34, 32, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_arrow_right", 96, 1560, 34, 32, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_arrow_up", 144, 1560, 32, 34, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_close", 184, 1560, 28, 32, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_gear", 224, 1560, 34, 30, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_heart_empty", 272, 1560, 26, 26, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_heart_full", 312, 1560, 26, 24, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_heart_half", 352, 1560, 26, 26, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_music", 392, 1560, 28, 32, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_orb_empty", 432, 1560, 27, 25, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_orb_full", 472, 1560, 24, 24, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_pause", 504, 1560, 27, 27, nil, nil, nil, nil, 196, 96, 176 },
  { "icon_speaker", 544, 1560, 32, 32, nil, nil, nil, nil, 196, 96, 176 },
}

local sprite = app.activeSprite
if sprite == nil or sprite.width ~= WIDTH or sprite.height ~= HEIGHT then
  sprite = Sprite{ fromFile = TEMPLATE, oneFrame = true }
end
if #sprite.slices > 0 then
  app.alert("This sprite already has slices, so nothing was added. Open ui-template.png afresh to start over.")
  return
end

app.transaction(function()
  for _, s in ipairs(SLICES) do
    local slice = sprite:newSlice(Rectangle(s[2], s[3], s[4], s[5]))
    slice.name = s[1]
    if s[6] ~= nil then
      slice.center = Rectangle(s[6], s[7], s[8], s[9])
    end
    slice.color = Color{ r = s[10], g = s[11], b = s[12], a = 255 }
  end
end)

local saved = ""
if app.fs.isFile(TARGET) then
  saved = "\n" .. TARGET .. " already exists, so the sprite was not saved over it (File > Save As to keep this one)."
else
  sprite:saveAs(TARGET)
  saved = "\nSaved as " .. TARGET
end
app.alert("Added " .. #SLICES .. " slices." .. saved)
